#!/usr/bin/env bash
# bootstrap-stage.sh — idempotent UAT seed for STAGE (tally-stage.lurus.cn).
#
# Seeds two fixed-UUID tenants + one PAT each, directly in the STAGE DB via
# `kubectl exec … psql` inside the backend pod (the only place raw SQL is
# allowed in the whole UAT harness). PAT plaintexts are generated LOCALLY with
# the exact algorithm of internal/domain/auth/pat.go:
#   prefix = base64url(6 random bytes)  -> 8 chars
#   secret = base64url(24 random bytes) -> 32 chars
#   hash   = hex(sha256(prefix || secret))
#   wire   = tally_pat_<prefix><secret>
#
# Idempotency: when .uat.env exists AND its primary PAT still authenticates
# (GET /api/v1/auth/pats lists "uat-primary"), this script is a no-op.
# Re-seeding inserts fresh PAT rows (old ones stay until pruned; per-tenant cap
# is generous) — tenants use ON CONFLICT DO NOTHING on fixed UUIDs.
#
# Out of scope by design: no k8s mutations, no deploys, no writes outside the
# two UAT-* tenants.
set -euo pipefail

UAT_DIR="$(cd "$(dirname "$0")" && pwd)"
ENV_FILE="$UAT_DIR/.uat.env"

UAT_BASE="${UAT_BASE:-https://tally-stage.lurus.cn}"
SSH_HOST="${SSH_HOST:-root@100.122.83.20}"
TENANT_PRIMARY="11111111-1111-1111-1111-111111111111"
TENANT_SECONDARY="22222222-2222-2222-2222-222222222222"
MIN_MIGRATION=48

# The backend image is scratch (no sh/psql), so we exec psql inside the PG pod
# (database/lurus-pg-0) using the backend's own DSN from tally-secrets — same
# role `tally` (NOSUPERUSER) the app uses, so RLS semantics match production.
# The DSN is expanded on R6 only; it never reaches this machine.
remote_psql() { # SQL on stdin -> rows on stdout (tuples-only, unaligned)
  ssh "$SSH_HOST" "DSN=\$(kubectl -n lurus-tally get secret tally-secrets -o jsonpath='{.data.DATABASE_DSN}' | base64 -d); kubectl -n database exec -i lurus-pg-0 -- psql \"\$DSN\" -tA -v ON_ERROR_STOP=1"
}

verify_pat() { # $1=pat $2=expected name; returns 0 when the PAT lists itself
  local body status
  body=$(mktemp)
  status=$(curl -sS -o "$body" -w '%{http_code}' \
    -H "Authorization: Bearer $1" "$UAT_BASE/api/v1/auth/pats" || echo 000)
  local ok=1
  if [ "$status" = "200" ] && jq -e --arg n "$2" \
      '(.items // .) | map(.name) | index($n) != null' "$body" >/dev/null 2>&1; then
    ok=0
  fi
  rm -f "$body"
  return "$ok"
}

# ---- short-circuit ---------------------------------------------------------
if [ -f "$ENV_FILE" ]; then
  # shellcheck disable=SC1090
  source "$ENV_FILE"
  if verify_pat "${UAT_PAT_PRIMARY:-}" uat-primary \
     && verify_pat "${UAT_PAT_SECONDARY:-}" uat-secondary; then
    echo "bootstrap: .uat.env present and both PATs authenticate — no-op"
    exit 0
  fi
  echo "bootstrap: .uat.env present but PATs no longer valid — re-seeding"
fi

command -v jq >/dev/null || { echo "FATAL: jq required" >&2; exit 1; }
command -v openssl >/dev/null || { echo "FATAL: openssl required" >&2; exit 1; }

# ---- preflight: migration head --------------------------------------------
HEAD=$(echo "SELECT version FROM tally.schema_migrations;" | remote_psql | tr -d '[:space:]')
case "$HEAD" in (*[!0-9]*|'') echo "FATAL: cannot read migration head (got '$HEAD')" >&2; exit 1;; esac
if [ "$HEAD" -lt "$MIN_MIGRATION" ]; then
  echo "FATAL: STAGE migration head $HEAD < required $MIN_MIGRATION" >&2
  exit 1
fi
echo "bootstrap: STAGE migration head = $HEAD (>= $MIN_MIGRATION ok)"

# ---- local PAT generation ---------------------------------------------------
gen_part() { openssl rand "$1" | base64 | tr '+/' '-_' | tr -d '=\n'; }
gen_pat() { # -> "wire hash" on stdout
  local prefix secret hash
  prefix=$(gen_part 6)   # 8 url-safe chars
  secret=$(gen_part 24)  # 32 url-safe chars
  hash=$(printf '%s%s' "$prefix" "$secret" | sha256sum | cut -d' ' -f1)
  echo "tally_pat_${prefix}${secret} $prefix $hash"
}

read -r PAT_P PREFIX_P HASH_P <<<"$(gen_pat)"
read -r PAT_S PREFIX_S HASH_S <<<"$(gen_pat)"

# ---- seed -------------------------------------------------------------------
# personal_access_token keeps the relaxed pre-auth RLS arm (000044): with no
# app.tenant_id GUC the policy passes, so plain inserts work. tenant has no
# tenant_id column / no isolation policy.
remote_psql <<SQL
INSERT INTO tally.tenant (id, name, status)
VALUES ('$TENANT_PRIMARY', 'UAT-PRIMARY', 1),
       ('$TENANT_SECONDARY', 'UAT-SECONDARY', 1)
ON CONFLICT (id) DO NOTHING;

INSERT INTO tally.personal_access_token (tenant_id, name, prefix, hash)
VALUES ('$TENANT_PRIMARY', 'uat-primary', '$PREFIX_P', '$HASH_P'),
       ('$TENANT_SECONDARY', 'uat-secondary', '$PREFIX_S', '$HASH_S')
ON CONFLICT (prefix) DO NOTHING;
SQL
echo "bootstrap: tenants + PATs inserted"

# ---- write env + verify through the real API --------------------------------
umask 077
cat >"$ENV_FILE" <<ENV
# Generated by bootstrap-stage.sh — gitignored, NEVER commit.
UAT_BASE=$UAT_BASE
UAT_TENANT_PRIMARY=$TENANT_PRIMARY
UAT_TENANT_SECONDARY=$TENANT_SECONDARY
UAT_PAT_PRIMARY=$PAT_P
UAT_PAT_SECONDARY=$PAT_S
ENV

verify_pat "$PAT_P" uat-primary || { echo "FATAL: primary PAT does not authenticate via $UAT_BASE" >&2; exit 1; }
verify_pat "$PAT_S" uat-secondary || { echo "FATAL: secondary PAT does not authenticate" >&2; exit 1; }
echo "bootstrap: both PATs verified live against $UAT_BASE — wrote $ENV_FILE"
