#!/usr/bin/env bash
# coverage.sh — compute endpoint coverage = (endpoints with pass evidence) /
# (deployed routes), write _uat-reports/coverage-matrix.md, exit 1 below 90%.
#
# Inputs:
#   scripts/uat/routes-deployed.txt — denominator (one "METHOD PATH" per line)
#   scripts/uat/registry.yaml       — case ledger. Field order inside each case
#     block is load-bearing for this parser: id, title, script, last_result,
#     last_run, ai_calls, failed_endpoints, endpoints. An endpoint counts as
#     covered when its case is last_result: pass, or last_result: partial and
#     the endpoint is NOT in that case's failed_endpoints (post-audit verdicts,
#     set by the workflow report phase — never by the tester itself).
#
# The percentage printed here is the only sanctioned number — never hand-derive.
set -euo pipefail

cd "$(dirname "$0")"
ROUTES="routes-deployed.txt"
REGISTRY="registry.yaml"
OUT="../../_uat-reports/coverage-matrix.md"
THRESHOLD_PCT=90

[ -f "$ROUTES" ] || { echo "FATAL: $ROUTES missing — run extract-routes.sh" >&2; exit 2; }
[ -f "$REGISTRY" ] || { echo "FATAL: $REGISTRY missing" >&2; exit 2; }

# Parse registry: emit "METHOD PATH|case|run" for every covered endpoint.
# section: 0=none, 1=failed_endpoints, 2=endpoints (failed_endpoints precedes
# endpoints in the mandated field order, so failures are known before counting).
COVERED_TMP="$(mktemp)"; FAILED_TMP="$(mktemp)"
trap 'rm -f "$COVERED_TMP" "$FAILED_TMP"' EXIT
cur_id="" cur_result="" cur_run="" section=0
while IFS= read -r line; do
  case "$line" in
    *'- id:'*)
      cur_id="${line##*- id: }"; cur_result=""; cur_run=""; section=0
      : >"$FAILED_TMP" ;;
    *'last_result:'*)
      cur_result="${line##*last_result: }"; section=0 ;;
    *'last_run:'*)
      cur_run="${line##*last_run: }"; cur_run="${cur_run//\"/}"; section=0 ;;
    *'failed_endpoints:'*)
      section=1 ;;
    *'endpoints:'*)
      section=2 ;;
    *'- "'*)
      ep="${line#*\"}"; ep="${ep%\"*}"
      if [ "$section" = 1 ]; then
        printf '%s\n' "$ep" >>"$FAILED_TMP"
      elif [ "$section" = 2 ]; then
        if [ "$cur_result" = "pass" ] || { [ "$cur_result" = "partial" ] && ! grep -qxF "$ep" "$FAILED_TMP"; }; then
          printf '%s|%s|%s\n' "$ep" "$cur_id" "$cur_run" >>"$COVERED_TMP"
        fi
      fi ;;
  esac
done <"$REGISTRY"

total=0 covered=0
{
  echo "# Tally STAGE UAT — Endpoint Coverage Matrix"
  echo ""
  echo "Generated by \`scripts/uat/coverage.sh\` — do not edit by hand."
  echo "Denominator: deployed commit routes (\`scripts/uat/routes-deployed.txt\`)."
  echo ""
  echo "| # | Endpoint | Covered | Case | Evidence |"
  echo "|---|----------|---------|------|----------|"
  while IFS= read -r route; do
    [ -n "$route" ] || continue
    total=$((total + 1))
    hits=$(grep -F "$route|" "$COVERED_TMP" || true)
    if [ -n "$hits" ]; then
      covered=$((covered + 1))
      cases=$(echo "$hits" | cut -d'|' -f2 | sort -u | paste -sd, -)
      first_case=$(echo "$hits" | head -1 | cut -d'|' -f2)
      first_run=$(echo "$hits" | head -1 | cut -d'|' -f3)
      echo "| $total | \`$route\` | ✅ | $cases | [evidence](evidence/$first_run/$first_case/) |"
    else
      echo "| $total | \`$route\` | ❌ | — | — |"
    fi
  done <"$ROUTES"
  echo ""
  pct=$((covered * 100 / total))
  echo "**Coverage: $covered / $total = ${pct}% (threshold ${THRESHOLD_PCT}%)**"
} >"$OUT"

# Drift check: registry endpoints that aren't deployed routes (typo or stale).
drift=$(cut -d'|' -f1 "$COVERED_TMP" | sort -u | while IFS= read -r ep; do
  grep -qxF "$ep" "$ROUTES" || echo "$ep"
done)
if [ -n "$drift" ]; then
  echo "WARNING: registry endpoints not in routes-deployed.txt (not counted):" >&2
  echo "$drift" >&2
fi

pct=$((covered * 100 / total))
echo "coverage: $covered/$total = ${pct}% -> $OUT"
if [ $((covered * 100)) -lt $((total * THRESHOLD_PCT)) ]; then
  echo "FAIL: coverage ${pct}% < ${THRESHOLD_PCT}%" >&2
  exit 1
fi
