package ai

import (
	"context"
	"fmt"

	"github.com/google/uuid"
	domainai "github.com/hanmahong5-arch/lurus-tally/internal/domain/ai"
	"github.com/hanmahong5-arch/lurus-tally/internal/pkg/llmclient"
)

// PlanStore persists and retrieves Plans (Redis-backed, TTL 1800s).
type PlanStore interface {
	// SavePlan stores a plan. Returns an error on failure.
	SavePlan(ctx context.Context, plan *domainai.Plan) error
	// GetPlan retrieves a plan by ID. Returns nil, nil when not found.
	GetPlan(ctx context.Context, tenantID, planID uuid.UUID) (*domainai.Plan, error)
	// UpdatePlan updates an existing plan's status.
	UpdatePlan(ctx context.Context, plan *domainai.Plan) error
}

// Orchestrator drives the multi-turn tool-calling loop.
// It calls the LLM, dispatches tool calls through the Registry, collects Plans,
// and streams the final text response.
type Orchestrator struct {
	llm       *llmclient.Client
	registry  *Registry
	planStore PlanStore
	model     string
}

// NewOrchestrator constructs an Orchestrator.
func NewOrchestrator(llm *llmclient.Client, registry *Registry, planStore PlanStore, model string) *Orchestrator {
	if model == "" {
		model = "deepseek-v4-flash"
	}
	return &Orchestrator{
		llm:       llm,
		registry:  registry,
		planStore: planStore,
		model:     model,
	}
}

// systemPrompt is the static inventory assistant persona.
// Kept as a constant to maximise prompt-cache hit rate (never put dynamic content here).
const systemPrompt = `You are an expert inventory management assistant for Tally, a Chinese B2B ERP system.
You have deep knowledge of inventory KPIs: ABC classification (Pareto 80/15/5), Re-Order Point (ROP = lead_time × avg_daily_sales + safety_stock), safety stock (z × σ × √lead_time), turnover rate, gross margin, and dead stock analysis.

You can call the provided tools to query real data from the user's inventory system. Always cite the data source in your response (e.g. "Based on 30 days of sales data...").

For DESTRUCTIVE operations (price changes, purchase orders, stock adjustments), you MUST call the propose_* tools. These tools return a plan_id that the user must confirm — you do NOT execute them directly. Inform the user that a confirmation card has been shown.

Respond in Chinese. Be concise and data-driven. When showing lists, limit to 10 items.`

// ChatInput is the input to a single chat turn.
type ChatInput struct {
	TenantID uuid.UUID
	// History is the conversation history (user + assistant turns).
	History []llmclient.Message
	// UserMessage is the new user message.
	UserMessage string
}

// ChatOutput is the result of a single chat turn.
type ChatOutput struct {
	// AssistantText is the final LLM response text (may include plan references).
	AssistantText string
	// Plans contains any Plans generated by destructive tool calls this turn.
	Plans []*domainai.Plan
	// ToolCalls records which tools were called.
	ToolCalls []domainai.ToolCallRecord
}

// maxToolRounds prevents infinite tool-call loops.
const maxToolRounds = 6

// Chat executes one user turn (non-streaming). Builds the full message sequence,
// runs tool-call rounds, and returns the final text + any plans.
func (o *Orchestrator) Chat(ctx context.Context, in ChatInput) (*ChatOutput, error) {
	messages := buildMessages(in)
	tools := ToolDefs()

	var plans []*domainai.Plan
	var toolCalls []domainai.ToolCallRecord

	for round := 0; round < maxToolRounds; round++ {
		resp, err := o.llm.Chat(ctx, o.model, messages, tools)
		if err != nil {
			return nil, fmt.Errorf("orchestrator: llm chat: %w", err)
		}
		if len(resp.Choices) == 0 {
			return nil, fmt.Errorf("orchestrator: no choices in response")
		}

		choice := resp.Choices[0]

		// If no tool calls, we have the final answer.
		if len(choice.Message.ToolCalls) == 0 {
			content, _ := extractContent(choice.Message.Content)
			return &ChatOutput{
				AssistantText: content,
				Plans:         plans,
				ToolCalls:     toolCalls,
			}, nil
		}

		// Append the full assistant message verbatim (trap 4: reasoning_content must survive).
		messages = append(messages, choice.Message)

		// Dispatch each tool call.
		for _, tc := range choice.Message.ToolCalls {
			result := o.registry.Dispatch(ctx, in.TenantID, tc)
			toolCalls = append(toolCalls, domainai.ToolCallRecord{
				ToolName:   tc.Function.Name,
				ArgsJSON:   tc.Function.Arguments,
				ResultJSON: result.Content,
			})

			// Persist plan if this was a destructive tool.
			if result.Plan != nil {
				if err := o.planStore.SavePlan(ctx, result.Plan); err != nil {
					// Non-fatal: log and continue; plan won't be confirmable.
					toolCalls[len(toolCalls)-1].Error = err
				} else {
					plans = append(plans, result.Plan)
				}
			}

			// Append the tool result message for the next LLM turn.
			messages = append(messages, llmclient.Message{
				Role:       "tool",
				Content:    result.Content,
				ToolCallID: tc.ID,
				Name:       tc.Function.Name,
			})
		}
	}

	return nil, fmt.Errorf("orchestrator: exceeded %d tool rounds without final answer", maxToolRounds)
}

// StreamChat executes one user turn and streams the response via onChunk.
// Tool calls are executed synchronously before streaming begins.
func (o *Orchestrator) StreamChat(ctx context.Context, in ChatInput, onChunk func(string)) (*ChatOutput, error) {
	messages := buildMessages(in)
	tools := ToolDefs()

	var plans []*domainai.Plan
	var toolCalls []domainai.ToolCallRecord

	// First do any tool-call rounds (non-streaming).
	for round := 0; round < maxToolRounds; round++ {
		resp, err := o.llm.Chat(ctx, o.model, messages, tools)
		if err != nil {
			return nil, fmt.Errorf("orchestrator: stream pre-tool chat: %w", err)
		}
		if len(resp.Choices) == 0 {
			return nil, fmt.Errorf("orchestrator: no choices")
		}
		choice := resp.Choices[0]

		if len(choice.Message.ToolCalls) == 0 {
			// No more tools — stream the final response.
			streamMessages := append(messages, choice.Message) //nolint:gocritic
			_ = streamMessages

			// Re-request with stream=true using the accumulated messages.
			var finalText string
			streamErr := o.llm.Stream(ctx, o.model, messages, nil, func(d llmclient.StreamDelta) {
				if d.Content != "" {
					onChunk(d.Content)
					finalText += d.Content
				}
			})
			if streamErr != nil {
				return nil, fmt.Errorf("orchestrator: stream final: %w", streamErr)
			}
			return &ChatOutput{
				AssistantText: finalText,
				Plans:         plans,
				ToolCalls:     toolCalls,
			}, nil
		}

		// Has tool calls — execute them first (non-streaming).
		messages = append(messages, choice.Message)
		for _, tc := range choice.Message.ToolCalls {
			result := o.registry.Dispatch(ctx, in.TenantID, tc)
			toolCalls = append(toolCalls, domainai.ToolCallRecord{
				ToolName:   tc.Function.Name,
				ArgsJSON:   tc.Function.Arguments,
				ResultJSON: result.Content,
			})
			if result.Plan != nil {
				if err := o.planStore.SavePlan(ctx, result.Plan); err != nil {
					toolCalls[len(toolCalls)-1].Error = err
				} else {
					plans = append(plans, result.Plan)
				}
			}
			messages = append(messages, llmclient.Message{
				Role:       "tool",
				Content:    result.Content,
				ToolCallID: tc.ID,
				Name:       tc.Function.Name,
			})
		}
	}

	return nil, fmt.Errorf("orchestrator: exceeded %d tool rounds", maxToolRounds)
}

// ConfirmPlan executes a confirmed plan. Currently a no-op stub:
// actual execution (price writes, purchase creation, stock adjust) will be
// wired in follow-up stories once the plan executor is implemented.
// Returns error if plan not found, already executed, or expired.
func (o *Orchestrator) ConfirmPlan(ctx context.Context, tenantID, planID uuid.UUID) (*domainai.Plan, error) {
	plan, err := o.planStore.GetPlan(ctx, tenantID, planID)
	if err != nil {
		return nil, fmt.Errorf("confirm plan: get: %w", err)
	}
	if plan == nil {
		return nil, ErrPlanNotFound
	}
	if plan.Status != domainai.PlanStatusPending {
		return nil, fmt.Errorf("confirm plan: plan is %s, cannot confirm", plan.Status)
	}
	plan.Status = domainai.PlanStatusConfirmed
	if err := o.planStore.UpdatePlan(ctx, plan); err != nil {
		return nil, fmt.Errorf("confirm plan: update: %w", err)
	}
	return plan, nil
}

// CancelPlan marks a plan as cancelled.
func (o *Orchestrator) CancelPlan(ctx context.Context, tenantID, planID uuid.UUID) error {
	plan, err := o.planStore.GetPlan(ctx, tenantID, planID)
	if err != nil {
		return fmt.Errorf("cancel plan: get: %w", err)
	}
	if plan == nil {
		return ErrPlanNotFound
	}
	if plan.Status != domainai.PlanStatusPending {
		return nil // already resolved — idempotent
	}
	plan.Status = domainai.PlanStatusCancelled
	return o.planStore.UpdatePlan(ctx, plan)
}

// ErrPlanNotFound is returned when a plan cannot be found in the store.
var ErrPlanNotFound = fmt.Errorf("plan not found or expired")

// buildMessages assembles the full message list for the LLM.
func buildMessages(in ChatInput) []llmclient.Message {
	msgs := make([]llmclient.Message, 0, 1+len(in.History)+1)
	msgs = append(msgs, llmclient.Message{Role: "system", Content: systemPrompt})
	msgs = append(msgs, in.History...)
	msgs = append(msgs, llmclient.Message{Role: "user", Content: in.UserMessage})
	return msgs
}

// extractContent handles both string and []interface{} content formats.
func extractContent(content interface{}) (string, bool) {
	switch v := content.(type) {
	case string:
		return v, true
	case nil:
		return "", false
	default:
		return fmt.Sprintf("%v", v), true
	}
}
