apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: ghcr.io/hanmahong5-arch/lurus-tally-backend
    newTag: main-a618eb3
  - name: ghcr.io/hanmahong5-arch/lurus-tally-web
    newTag: main-a618eb3
