/**
 * UAT STAGE setup — authenticate against a LOCAL next dev (port 3030) whose
 * BACKEND_URL points at the real STAGE backend (https://tally-stage.lurus.cn).
 *
 * Login is done purely over the NextAuth REST flow (no UI):
 *   1. GET  /api/auth/csrf                   → csrfToken + csrf cookie
 *   2. POST /api/auth/callback/credentials   → session cookie (dev provider)
 *   3. GET  /api/auth/session                → verify tenantId round-trips
 *   4. storageState saved for the chromium-uat-stage project.
 *
 * Credentials come from scripts/uat/.uat.env (generated by
 * scripts/uat/bootstrap-stage.sh, gitignored). Token values are never logged.
 */

import { test, expect } from "@playwright/test"
import path from "path"
import fs from "fs"

const STATE_FILE = path.resolve(__dirname, "../../test-results-uat/uat-stage-state.json")
const UAT_ENV_FILE = path.resolve(__dirname, "../../../scripts/uat/.uat.env")

/** Parses scripts/uat/.uat.env (simple KEY=VALUE lines, # comments). */
function loadUatEnv(): Record<string, string> {
  if (!fs.existsSync(UAT_ENV_FILE)) {
    throw new Error(
      `Missing ${UAT_ENV_FILE} — run scripts/uat/bootstrap-stage.sh first to mint STAGE tenant + PAT.`,
    )
  }
  const out: Record<string, string> = {}
  for (const line of fs.readFileSync(UAT_ENV_FILE, "utf8").split(/\r?\n/)) {
    const trimmed = line.trim()
    if (!trimmed || trimmed.startsWith("#")) continue
    const eq = trimmed.indexOf("=")
    if (eq <= 0) continue
    out[trimmed.slice(0, eq)] = trimmed.slice(eq + 1)
  }
  return out
}

test("login via dev credentials provider with STAGE PAT", async ({ request }) => {
  const env = loadUatEnv()
  const tenantId = env.UAT_TENANT_PRIMARY
  const pat = env.UAT_PAT_PRIMARY
  if (!tenantId || !pat) {
    throw new Error(
      "UAT_TENANT_PRIMARY / UAT_PAT_PRIMARY missing in scripts/uat/.uat.env — " +
        "re-run scripts/uat/bootstrap-stage.sh.",
    )
  }

  // 1. CSRF token (cookie is kept inside this APIRequestContext).
  const csrfRes = await request.get("/api/auth/csrf")
  expect(csrfRes.ok(), `GET /api/auth/csrf → ${csrfRes.status()}`).toBeTruthy()
  const { csrfToken } = (await csrfRes.json()) as { csrfToken: string }
  expect(csrfToken, "csrfToken present").toBeTruthy()

  // 2. Credentials sign-in. The dev provider passes accessToken (the STAGE PAT)
  //    through to the session so /api/proxy/* forwards it as Bearer.
  const cbRes = await request.post("/api/auth/callback/credentials", {
    form: {
      csrfToken,
      email: "uat@tally.test",
      tenantId,
      accessToken: pat,
      redirect: "false",
      callbackUrl: "/dashboard",
      json: "true",
    },
  })
  // Redirects are followed automatically; any 4xx/5xx means sign-in failed.
  expect(
    cbRes.status(),
    "POST /api/auth/callback/credentials must succeed (is AUTH_DEV_PROVIDER=true on the dev server?)",
  ).toBeLessThan(400)

  // 3. Session must round-trip the tenantId we signed in with.
  const sessionRes = await request.get("/api/auth/session")
  expect(sessionRes.ok(), `GET /api/auth/session → ${sessionRes.status()}`).toBeTruthy()
  const session = (await sessionRes.json()) as {
    user?: { tenantId?: string | null }
  } | null
  expect(session?.user?.tenantId, "session.user.tenantId matches UAT tenant").toBe(tenantId)

  // 4. Persist cookies for the dependent chromium-uat-stage project.
  fs.mkdirSync(path.dirname(STATE_FILE), { recursive: true })
  await request.storageState({ path: STATE_FILE })
})

test("dev provider only present because AUTH_DEV_PROVIDER=true", async ({ request }) => {
  // Production-inertness contract: this local dev server runs with
  // AUTH_DEV_PROVIDER=true and NODE_ENV !== "production", so the "credentials"
  // provider MUST be listed. The inverse guarantee — that the provider is
  // ABSENT in production — cannot be observed from this server; it is enforced
  // by the double gate in devProviderEnabled() (web/auth.ts): the provider is
  // only appended when AUTH_DEV_PROVIDER === "true" AND NODE_ENV !== "production",
  // and production refuses with a console.error even if the env var leaks in.
  const res = await request.get("/api/auth/providers")
  expect(res.ok(), `GET /api/auth/providers → ${res.status()}`).toBeTruthy()
  const providers = (await res.json()) as Record<string, unknown>
  expect(Object.keys(providers), "credentials provider listed on dev server").toContain(
    "credentials",
  )
})
